version: "3"
services:
  app:
    image: car-showcase-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.car-hub.rule=Host(`carhub.abubakarkhalid.com`)"
      - "traefik.http.routers.car-hub.entrypoints=websecure"
      - "traefik.http.routers.car-hub.tls=true"
      - "traefik.http.routers.car-hub.tls.certresolver=myresolver"
    networks:
      - traefik
networks:
  traefik:
    external: true