name: Docker Image CI for GHCR

on:
  push

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build and publish the image
        run: |
          docker login --username abk007 --password ${{secrets.GH_AT}} ghcr.io
          docker build . --tag ghcr.io/abk007/car-showcase-app-ghcr:latest
          docker push ghcr.io/abk007/car-showcase-app-ghcr:latest

